# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/hackrf2tcp',
                'doc_host': 'https://ronaldokun.github.io',
                'git_url': 'https://github.com/ronaldokun/hackrf2tcp',
                'lib_path': 'hackrf2tcp'},
  'syms': {'hackrf2tcp.core': {'hackrf2tcp.core.foo': ('core.html#foo', 'hackrf2tcp/core.py')}}}